//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_req_mini
    {
        public int MINI_ID { get; set; }
        public string MINI_CODE { get; set; }
        public string USER_NO { get; set; }
        public Nullable<System.DateTime> MINI_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string MINI_SAMPLE { get; set; }
        public string MINI_PROTO { get; set; }
        public string MINI_INFORM { get; set; }
        public string MINI_CHM { get; set; }
        public string MINI_REQUESTER { get; set; }
        public string MINI_APPROVE_OWNER { get; set; }
        public Nullable<System.DateTime> MINI_APPROVE_OWNER_DATE { get; set; }
        public string MINI_APPROVE { get; set; }
        public Nullable<System.DateTime> MINI_APPROVE_DATE { get; set; }
        public string MINI_OPEN_BY { get; set; }
        public Nullable<System.DateTime> MINI_OPEN_DATE { get; set; }
        public string MINI_ASSIGN_TO { get; set; }
        public Nullable<System.DateTime> MINI_ASSIGN_DATE { get; set; }
        public Nullable<System.DateTime> MINI_SUBMIT_DATE { get; set; }
        public string MINI_CLOSE { get; set; }
        public Nullable<System.DateTime> MINI_CLOSE_DATE { get; set; }
        public string REQ_STATUS { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string MINI_IT_COMMENT { get; set; }
        public string MINI_IT_COMMENTER { get; set; }
        public string MINI_IT_MANAGER { get; set; }
        public Nullable<System.DateTime> MINI_IT_DATE { get; set; }
    }
}
