//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_req_allow_status
    {
        public string ALLOW_STATUS { get; set; }
        public string ALLOW_DESC { get; set; }
    }
}
