//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_req_member
    {
        public int MEM_ID { get; set; }
        public string MEM_NO { get; set; }
        public string NAME_TH { get; set; }
        public string NAME_EN { get; set; }
        public string MEM_POSITION { get; set; }
        public string MEM_DEPARTMENT { get; set; }
        public string MEM_EXTENSION { get; set; }
    }
}
