//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_req_af
    {
        public int AF_ID { get; set; }
        public string AF_CODE { get; set; }
        public string USER_NO { get; set; }
        public Nullable<System.DateTime> AF_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string AF_SITE { get; set; }
        public string AF_FOLDER { get; set; }
        public string AF_STATUS { get; set; }
        public string AF_NOTE { get; set; }
        public string AF_REQUESTER { get; set; }
        public string AF_APPROVE_OWNER { get; set; }
        public Nullable<System.DateTime> AF_APPROVE_OWNER_DATE { get; set; }
        public string AF_APPROVE { get; set; }
        public Nullable<System.DateTime> AF_APPROVE_DATE { get; set; }
        public string AF_OPEN_BY { get; set; }
        public Nullable<System.DateTime> AF_OPEN_DATE { get; set; }
        public string AF_ASSIGN_TO { get; set; }
        public Nullable<System.DateTime> AF_ASSIGN_DATE { get; set; }
        public Nullable<System.DateTime> AF_SUBMIT_DATE { get; set; }
        public string AF_CLOSE { get; set; }
        public Nullable<System.DateTime> AF_CLOSE_DATE { get; set; }
        public string REQ_STATUS { get; set; }
        public string AF_BILL_NO { get; set; }
        public Nullable<System.DateTime> AF_BILL_DATE { get; set; }
        public Nullable<float> AF_COST { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string AF_IT_COMMENT { get; set; }
        public string AF_IT_COMMENTER { get; set; }
        public string AF_IT_MANAGER { get; set; }
        public Nullable<System.DateTime> AF_IT_DATE { get; set; }
    }
}
