//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_req_af_register
    {
        public string AF_CODE { get; set; }
        public string MEM_NO { get; set; }
        public string USER_NO { get; set; }
        public string MEM_NAME { get; set; }
        public string MEM_NAME_EN { get; set; }
        public string MEM_POSITION { get; set; }
        public string MEM_DEPARTMENT { get; set; }
        public string MEM_EXTENSION { get; set; }
        public string MEM_EMAIL { get; set; }
        public string MEM_ROLE { get; set; }
        public Nullable<System.DateTime> AF_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string ALLOW_DESC { get; set; }
        public string ID_APPLICANT { get; set; }
        public string APPLICANT_DESC { get; set; }
        public string AF_SITE { get; set; }
        public string AF_FOLDER { get; set; }
        public string AF_STATUS { get; set; }
        public string AF_STATUS_NAME { get; set; }
        public string AF_NOTE { get; set; }
        public string AF_REQUESTER { get; set; }
        public string USER_NAME { get; set; }
        public string USER_EXTENSION { get; set; }
        public string USER_EMAIL { get; set; }
        public string REQ_STATUS { get; set; }
        public string STA_DESC { get; set; }
    }
}
