//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_document
    {
        public int DOC_ID { get; set; }
        public string DOC_NO { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_YEAR { get; set; }
        public string DOC_DESCRIPTION { get; set; }
        public int DOC_TYPE { get; set; }
        public string SUPPLIER { get; set; }
        public Nullable<System.DateTime> DOC_START_DATE { get; set; }
        public Nullable<System.DateTime> DOC_END_DATE { get; set; }
        public string COST_ID { get; set; }
        public string DOC_LOCATION_REF { get; set; }
        public string DOC_REFERENCE_COM { get; set; }
        public string DOC_REFERENCE_DOC { get; set; }
        public string DOC_ATTACH { get; set; }
        public string DOC_REMARK { get; set; }
        public string DOC_STATUS { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int HW_WARANTEE { get; set; }
        public int HW_WAR_YEAR { get; set; }
        public string DOC_TYPE_DESC { get; set; }
        public string DOC_GROUP { get; set; }
        public string COST_SECTION { get; set; }
    }
}
