//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_req_sd
    {
        public string SD_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NAME_EN { get; set; }
        public string USER_POSITION { get; set; }
        public string USER_DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public string USER_EMAIL { get; set; }
        public Nullable<System.DateTime> SD_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string ALLOW_DESC { get; set; }
        public string SD_DRIVE { get; set; }
        public string SD_FOLDER { get; set; }
        public string SD_NOTE { get; set; }
        public string REQ_AUTH { get; set; }
        public string AUTH_DESC { get; set; }
        public string SD_REQUESTER { get; set; }
        public string REQUESTER_NAME { get; set; }
        public string REQUESTER_EN_NAME { get; set; }
        public string REQUESTER_POSITION { get; set; }
        public string REQUESTER_DEPARTMENT { get; set; }
        public string REQUESTER_EXTENSION { get; set; }
        public string REQUESTER_EMAIL { get; set; }
        public string SD_APPROVE_OWNER { get; set; }
        public Nullable<System.DateTime> SD_APPROVE_OWNER_DATE { get; set; }
        public string SD_APPROVE { get; set; }
        public Nullable<System.DateTime> SD_APPROVE_DATE { get; set; }
        public string REQ_STATUS { get; set; }
        public string STA_DESC { get; set; }
    }
}
