//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_req_mini_follow
    {
        public string MINI_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NAME_EN { get; set; }
        public string USER_POSITION { get; set; }
        public string USER_DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_EMAIL_APPROVE { get; set; }
        public Nullable<System.DateTime> MINI_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string MINI_SAMPLE { get; set; }
        public string MINI_PROTO { get; set; }
        public string MINI_INFORM { get; set; }
        public string MINI_CHM { get; set; }
        public string MINI_REQUESTER { get; set; }
        public string REQUESTER_NAME { get; set; }
        public string REQUESTER_EN_NAME { get; set; }
        public string REQUESTER_POSITION { get; set; }
        public string REQUESTER_DEPARTMENT { get; set; }
        public string REQUESTER_EXTENSION { get; set; }
        public string REQUESTER_EMAIL { get; set; }
        public string REQUESTER_EMAIL_APPROVE { get; set; }
        public string MINI_APPROVE_OWNER { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_EN_NAME { get; set; }
        public string OWNER_POSITION { get; set; }
        public string OWNER_DEPARTMENT { get; set; }
        public string OWNER_EXTENSION { get; set; }
        public string OWNER_EMAIL { get; set; }
        public string OWNER_EMAIL_APPROVE { get; set; }
        public Nullable<System.DateTime> MINI_APPROVE_OWNER_DATE { get; set; }
        public string MINI_APPROVE { get; set; }
        public string APPROVE_NAME { get; set; }
        public string APPROVE_EN_NAME { get; set; }
        public string APPROVE_POSITION { get; set; }
        public string APPROVE_DEPARTMENT { get; set; }
        public string APPROVE_EXTENSION { get; set; }
        public string APPROVE_EMAIL { get; set; }
        public string APPROVE_EMAIL_APPROVE { get; set; }
        public Nullable<System.DateTime> MINI_APPROVE_DATE { get; set; }
        public string MINI_OPEN_BY { get; set; }
        public string OPEN_NAME { get; set; }
        public string OPEN_SURNAME { get; set; }
        public Nullable<System.DateTime> MINI_OPEN_DATE { get; set; }
        public string MINI_ASSIGN_TO { get; set; }
        public string ASSIGN_NAME { get; set; }
        public string ASSIGN_SURNAME { get; set; }
        public Nullable<System.DateTime> MINI_ASSIGN_DATE { get; set; }
        public string MINI_CLOSE { get; set; }
        public string CLOSE_NAME { get; set; }
        public string CLOSE_SURNAME { get; set; }
        public Nullable<System.DateTime> MINI_CLOSE_DATE { get; set; }
        public string REQ_STATUS { get; set; }
        public string MINI_IT_COMMENT { get; set; }
        public string MINI_IT_COMMENTER { get; set; }
        public string MINI_IT_MANAGER { get; set; }
        public Nullable<System.DateTime> MINI_IT_DATE { get; set; }
        public string STA_DESC { get; set; }
        public string ALLOW_DESC { get; set; }
    }
}
