//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_ASSET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_req_af_follow
    {
        public string AF_CODE { get; set; }
        public string MEM_NO { get; set; }
        public string APPLICANT_NO { get; set; }
        public string APPLICANT_NAME { get; set; }
        public string APPLICANT_NAME_EN { get; set; }
        public string APPLICANT_POSITION { get; set; }
        public string APPLICANT_DEPARTMENT { get; set; }
        public string APPLICANT_EXTENSION { get; set; }
        public string APPLICANT_EMAIL { get; set; }
        public string APPLICANT_ROLE { get; set; }
        public Nullable<System.DateTime> AF_DATE { get; set; }
        public string ALLOW_STATUS { get; set; }
        public string ALLOW_DESC { get; set; }
        public string ID_APPLICANT { get; set; }
        public string APPLICANT_DESC { get; set; }
        public string AF_SITE { get; set; }
        public string AF_FOLDER { get; set; }
        public string AF_STATUS { get; set; }
        public string AF_STATUS_NAME { get; set; }
        public string AF_NOTE { get; set; }
        public string AF_REQUESTER { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NAME_EN { get; set; }
        public string USER_POSITION { get; set; }
        public string USER_DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_ROLE { get; set; }
        public string AF_APPROVE_OWNER { get; set; }
        public string REQ_STATUS { get; set; }
        public string STA_DESC { get; set; }
        public Nullable<System.DateTime> AF_APPROVE_OWNER_DATE { get; set; }
        public string AF_APPROVE { get; set; }
        public Nullable<System.DateTime> AF_APPROVE_DATE { get; set; }
        public string APPROVE_NO { get; set; }
        public string APPROVE_NAME { get; set; }
        public string APPROVE_NAME_EN { get; set; }
        public string APPROVE_POSITION { get; set; }
        public string APPROVE_DEPARTMENT { get; set; }
        public string APPROVE_EXTENSION { get; set; }
        public string APPROVE_EMAIL { get; set; }
        public string APPROVE_ROLE { get; set; }
        public string AF_OPEN_BY { get; set; }
        public string IT_OPEN_BY_NAME { get; set; }
        public string IT_OPEN_BY_SURNAME { get; set; }
        public Nullable<System.DateTime> AF_OPEN_DATE { get; set; }
        public string AF_ASSIGN_TO { get; set; }
        public string IT_ASSIGN_NAME { get; set; }
        public string IT_ASSIGN_SURMANE { get; set; }
        public Nullable<System.DateTime> AF_ASSIGN_DATE { get; set; }
        public string AF_CLOSE { get; set; }
        public Nullable<System.DateTime> AF_CLOSE_DATE { get; set; }
    }
}
